---
openapi: 3.0.0
info:
   version: 1.3.0
   title: testingcurdapp open api specification
   description: studentallapp API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8017
     description: studentallapp
tags:
- name: detailsstudent
paths:
   "/detailsstudent":
      get:
         tags:
         -  detailsstudent
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      detailsstudent:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            age:
               type: "string"
               description: Description